name: colocators-ohw19
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter
  - jupyterlab
  - ipyleaflet
  - ipywidgets
  - hvplot
  - cmocean
  - datashader
  - geoviews
  - holoviews
  - panel
  - voila
  - compliance-checker
  - pandas
  - requests
  - erddapy
  - cartopy
  - matplotlib
  - numpy
  - palettable
  - iris
  - folium
  - pip
  - pip:
    - git+https://github.com/oceanhackweek/ohw19-project-co_locators.git
